# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "459512c8-c671-44b3-858d-c50fa9060635"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
  build_android_app(task: "assembleRelease")

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "8b6455ddb642545dd16491543aeeedbb8e895815",
    build_secret: "a071aefadc83ad33a3552614f6c00b3f04d607c5ed14064c288ce460f6a64416"
  )
end
